### ISSUE TITLE
Django: djLint changes {% blocktranslate %} if not using trimmed strings

### ISSUE THREAD

**Issue by matthiask** [Riverside-Healthcare/djLint#26]
This may or may not be a problem. I think I like the fact that `{% blocktranslate %}` tags are formatted as well, but without `trimmed` the original string changes each time the template is reindented and that's a bit bad.

Maybe this is something to add, for example in a new recommendations section.

**Comment by christopherpickering** [comment]
Do you have a html code block handy that I can test with?

**Comment by christopherpickering** [comment]
I tested out blocktanslate on a bunch of templates but can't find the problem you're referencing.
```html
{% load i18n %}
{% blocktranslate with content_object=note.content_object %}New note on {{ content_object }}{% endblocktranslate %}

{% blocktranslate with created_by=note.created_by content_object=note.content_object trimmed %}
{{ created_by }} just created a new note on "{{ content_object }}":
{% endblocktranslate %}

{{ note.title }}
{{ note.description }}

{{ url }}
``` 
becomes: 

```html
{% load i18n %}
{% blocktranslate with content_object=note.content_object %}
    New note on {{ content_object }}
{% endblocktranslate %}
{% blocktranslate with created_by=note.created_by content_object=note.content_object trimmed %}
    {{ created_by }} just created a new note on "{{ content_object }}":
{% endblocktranslate %}
{{ note.title }}
{{ note.description }}
{{ url }}
```

and if I run ``--check`` on this, there are 0 updates.

**Comment by matthiask** [comment]
I mean this scenario:

```
<div>
    {% blocktranslate %}
        Original string
    {% endblocktranslate %}
</div>
```

```
<div><div>
    {% blocktranslate %}
        Original string
    {% endblocktranslate %}
</div></div>
```

Running djLint on the second blob indents the "Original string" more (which is what it is supposed to do) but the original string changes because of the additional whitespace. At least I think it does.

**Comment by christopherpickering** [comment]
Ah I think I understand. I've never used blocktranslate.. but from what you say, it sounds like django treats it like a ``<textarea>`` and keeps all space inside it as literal? I'll have to check that out more.

**Comment by christopherpickering** [comment]
It sounds really odd.. the docs don't say anything about it. https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#std:templatetag-blocktranslate

Are you compressing your html? The whitespace should be done away with then.

**Comment by christopherpickering** [comment]
Do you have a live site w/ it I can check out?

**Comment by matthiask** [comment]
(Sorry for the slow response time.)

Unfortunately I'm not sure I have a public repo somewhere, but here are two screenshots:

![image](https://user-images.githubusercontent.com/2627/134909514-bb137dcf-b855-437c-b154-800f845d573f.png)

![image](https://user-images.githubusercontent.com/2627/134909539-9848652e-d8d0-4d18-8456-df767de340d5.png)

As you can see the indentation is part of the original string (as I would expect)

This is mentioned while describing the `trimmed` option in the official docs you linked to:

> Another feature {% blocktranslate %} supports is the trimmed option. This option will remove newline characters from the beginning and the end of the content of the {% blocktranslate %} tag, replace any whitespace at the beginning and end of a line and merge all lines into one using a space character to separate them. This is quite useful for indenting the content of a {% blocktranslate %} tag without having the indentation characters end up in the corresponding entry in the PO file, which makes the translation process easier.

So I'm really not sure whether there is a bug at all here, but it's definitely something to be aware of when changing the contents of `{% blocktranslate %}` blocks.

Or maybe it is a misbehavior to change the contents of a `{% blocktranslate %}` block exactly because gettext so strongly requires the original string to stay the same.

**Comment by christopherpickering** [comment]
Ok, thanks for the examples! I will look closer into it as well.

**Comment by jayvdb** [comment]
Changing the indentation of `blocktranslate` without `trimmed` does cause problems wrt to the .po files, however this is the reason why fuzzy translations are supported -- minor changes to existing translatable strings.

However fuzzy translations can introduce lots of problems if the dev team are not carefully checking the .po changes, and/or translators are not involved in the dev process, or the translation tooling dont support fuzzy.

IMO it would be useful to have a "ignore-untrimmed-blocktranslate" option for the reformatter.  Or have that enabled by default (safer) and have a "reformat-untrimmed-blocktranslate" option.

But ... an even better approach would be to also update the .po file when reformatting the `blocktranslate`, so that it is a non-fuzzy update, thereby getting the best of both worlds.  I'm keen to (quickly) add po support to djlint for other reasons, so we'd be able to leverage that to also update the .po when the reformatter touches a string in the .po file.

Where I normally see intentionally untrimmed blocktranslate is in email templates.

Most other times, the `blocktranslate` should have been trimmed but wasnt because the dev forgot, so I would really like a lint rule which recommends using `blocktranslate trimmed` as long as I can ignore that rule for files `**/*.txt`

**Comment by matthiask** [comment]
> Most other times, the blocktranslate should have been trimmed but wasnt because the dev forgot, so I would really like a lint rule which recommends using blocktranslate trimmed as long as I can ignore that rule for files **/*.txt

That was exactly the reason why I added the `extend_exclude` option btw; unfortunately Django's password reset mail template uses a `.html` extension.

**Comment by jayvdb** [comment]
> unfortunately Django's password reset mail template uses a .html extension.

iirc, last major project I worked on solved this by having the .html(s) include a .txt of the same name.

**Comment by christopherpickering** [comment]
Thanks, any chance you can share snippets of a trimmed vs untrimmed block? I'm not familiar w/ the translate tools.

**Comment by christopherpickering** [comment]
Are you guys on discord? https://discord.gg/taghAqebzU
