### ISSUE TITLE
[FEATURE] add a regular pre-commit hook 

### ISSUE THREAD

**Issue by 12rambau** [Riverside-Healthcare/djLint#430]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

I started using djlint because I wanted to improve the way I write html code in a pydata project. I wanted to setup djlint on my repository so I created a .djlintrc file with some parameters. now I would like to use the pre-commit hook which is super handy as I would run djlint for every single commit. 

Why isn't there a "regular" djlint that would simply read the .djlint file to know my custom parameters ? that's what flake8 and Black are doing and it work like a charm

In my use case I use jinja templating in .html file and not .j2 and I find it redundant to set it in both the djlinrc file AND the pre-commit-config.yaml

**Comment by christopherpickering** [comment]
Hi @12rambau,

I'm not sure I fully understand what you are looking for.

Its easy for pre-commit to know that `.py` files are python (for black, flake8, etc) , but not easy for them to know that `.html` is jinja vs django or nunjucks, or just plain old html, so you must set that in the pre-commit settings.

Otherwise are you saying that djLint isn't finding your `.djlintrc` file? Are you using a pre-commit hook like this https://djlint.com/docs/integrations/ ?

Thanks!

**Comment by 12rambau** [comment]
I think I get now why I need to set the file type in the pre-commit hook (as it's only triggered for a specfic file type) but I fail to understand why I need to choose between `djlint-django`or `djlint-jinja` when the profile is already set in my .djlintrc.

I would expect for custom is something like: 

```yaml
repos:
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 0.5.10 # grab latest tag from GitHub
    hooks:
      - id: djlint
        types_or: ['html']
```

and this hook would use all the parameters from my `.djlintrc` even the "profile"

**Comment by christopherpickering** [comment]
closing for now, please reply back if there is an issue.

Thanks!
