### ISSUE TITLE
[FEATURE] Lint indent

### ISSUE THREAD

**Issue by jayvdb** [Riverside-Healthcare/djLint#55]
- [x] I've searched the [issues](https://github.com/Riverside-Healthcare/djLint/issues)
- [x] I've read the [docs](https://djlint.com)

## Feature Request

The reformatter performs indenting, however there isnt a lint error for incorrect indentation.

**Comment by christopherpickering** [comment]
I thought about this as well, but probably will not add this. It would involve running the ``--check`` option and then attempting to map input to output to generate error messages.

A 1/2 way approach would be to run the diff from the indent.py file and see what lines would get more indentation. I'm not a fan of this completely as it ignores other formatting issues..... which is why I'm a fan of keeping linting for html "problems" and formatting for how it "looks".

**Comment by jayvdb** [comment]
For me, the main reason for wanting this is to have a single error report, instead of having two types of error reports.

This touches on https://github.com/Riverside-Healthcare/djLint/issues/18 a bit.

But I can appreciate it isnt easy to achieve at the moment, and there are bigger fish to fry.  Keeping them separate does have its advantages.
